name = "evefan-test"
main = "dist/index.js"
compatibility_date = "2024-07-01"

[build]
command = "npm run build"
## Not existing directory so that it doesn't watch
watch_dir = "/dir"

[durable_objects]
bindings = [
  { name = "BATCHER", class_name = "Batcher" }
]

[[migrations]]
tag = "v1"
new_classes = ["Batcher"]